import type {
  OrderListRow,
  RequisitionCase,
} from "../_types/order-management.type";

export const ORDER_LIST_MOCK: OrderListRow[] = [
  {
    orderId: "ORD-8892",
    date: "12/01/2025",
    officeName: "নোয়াখালী সদর",
    officeCode: "DC-NOA-001",
    economicCode: "2111113",
    vendorName: "Computer Source Ltd",
    total: { currency: "BDT", amount: 650000 },
    currentStage: "NEGOTIATION",
  },
  {
    orderId: "ORD-8875",
    date: "10/01/2025",
    officeName: "উপজেলা নির্বাহী অফিস",
    officeCode: "UNO-SAV-04",
    economicCode: "2211101",
    vendorName: "Global Brand Pvt Ltd",
    total: { currency: "BDT", amount: 120000 },
    currentStage: "COMPLETED",
  },
  {
    orderId: "ORD-8850",
    date: "08/01/2025",
    officeName: "জেলা প্রশাসকের কার্যালয়",
    officeCode: "DC-GZP-01",
    economicCode: "2111113",
    vendorName: "Flora Limited",
    total: { currency: "BDT", amount: 485000 },
    currentStage: "PAYMENT",
  },
  {
    orderId: "ORD-8812",
    date: "05/01/2025",
    officeName: "মৎস্য অধিদপ্তর",
    officeCode: "DOF-HQ-22",
    economicCode: "3111105",
    vendorName: "Smart Technologies",
    total: { currency: "BDT", amount: 152000 },
    currentStage: "PROCESSING",
  },
];

export const REQ_CASE_MOCK: RequisitionCase = {
  reqId: "REQ-8892",
  officeName: "নোয়াখালী সদর উপজেলা",
  createdAt: "২০ মে, ২০২৪",
  currentStep: "requisition",
  steps: [
    { key: "requisition", label: "রিকুইজিশন", done: true },
    { key: "discussion", label: "আলোচনা", done: true },
    { key: "office_confirmation", label: "অফিস কনফার্মেশন", done: true },
    { key: "payment_verify", label: "পেমেন্ট ভেরিফাই", done: false },
    { key: "shipment", label: "শিপমেন্ট", done: false },
    { key: "final_settlement", label: "ফাইনাল সেটেলমেন্ট", done: false },
  ],
  items: [
    {
      itemId: "ITEM-4918",
      title: "এ৪ পেপার",
      orderId: "ORD-4918",
      internalId: "3255101",
      payment: {
        office: {
          officeCode: "1002-Finance-Dept",
          payeeName: "মেসার্স রবিন এন্টারপ্রাইজ",
          refNo: "REF-998210",
          enteredAmount: { currency: "BDT", amount: 50000 },
          matchStatus: "MATCHED",
          notes:
            "সেপ্টেম্বর ২০২৩ মাসের টোনার এবং আনুষঙ্গিক মালামাল সরবরাহের পেমেন্ট ডাটা সাবমিট করা হয়েছে।",
          invoice: {
            id: "INV-1",
            name: "Invoice_Sep2023.pdf",
            sizeText: "2.4 MB",
            uploadedOn: "20 May",
          },
          status: "PENDING",
          totalAmount: { currency: "BDT", amount: 150000 },
          pendingAmount: { currency: "BDT", amount: 5000 },
          transactions: [
            {
              id: "TX-1",
              date: "১ মে ২০২৪",
              refNo: "REF-9901",
              amount: { currency: "BDT", amount: 10000 },
              status: "COMPLETED",
            },
            {
              id: "TX-2",
              date: "২ মে ২০২৪",
              refNo: "REF-998210",
              amount: { currency: "BDT", amount: 5000 },
              status: "PENDING",
            },
          ],
        },
        vendor: {
          status: "OPEN",
          invoiceTotal: { currency: "BDT", amount: 100000 },
          officeAdvancePercent: 80,
          officeAdvanceAmount: { currency: "BDT", amount: 80000 },
          vendorDuePercent: 80,
          vendorDueAmount: { currency: "BDT", amount: 80000 },
          pendingAmount: { currency: "BDT", amount: 60000 },
          bank: {
            bankName: "সোনালী ব্যাংক পিএলসি",
            accountName: "মেসার্স রবিন এন্টারপ্রাইজ",
            accountNo: "১২৩৪৫৬৭৮৯০",
            routingNo: "০৩০২৬১...",
            branchName: "মটিহিল কর্পোরেট শাখা",
          },
        },
      },
      shipment: {
        status: "AGENT_REQUIRED",
      },
      settlement: {
        status: "PENDING_DETAIL",
        total: { currency: "BDT", amount: 15000 },
        cleared: { currency: "BDT", amount: 10000 },
        pending: { currency: "BDT", amount: 5000 },
        deductions: [
          {
            label: "ভ্যাট (VAT)",
            percentText: "৫%",
            amount: { currency: "BDT", amount: 160.89 },
          },
          {
            label: "আইটি (IT)",
            percentText: "২%",
            amount: { currency: "BDT", amount: 64.19 },
          },
          {
            label: "অতিরিক্ত ভ্যাট",
            percentText: "০.৪%",
            amount: { currency: "BDT", amount: 16.05 },
          },
        ],
        ledgerRows: [
          {
            date: "১৫ মে, ২০২৪",
            refNo: "EFT-992312-A",
            amount: { currency: "BDT", amount: 2000 },
          },
          {
            date: "১৬ মে, ২০২৪",
            refNo: "EFT-992455-B",
            amount: { currency: "BDT", amount: 2000 },
          },
          {
            date: "১৮ মে, ২০২৪",
            refNo: "EFT-992678-C",
            amount: { currency: "BDT", amount: 2000 },
          },
        ],
      },
    },
    {
      itemId: "ITEM-4922",
      title: "এইচপি লেজার টোনার",
      orderId: "ORD-4922",
      internalId: "3255102",
      payment: {
        office: {
          officeCode: "1002-Finance-Dept",
          payeeName: "মেসার্স রবিন এন্টারপ্রাইজ",
          refNo: "REF-998211",
          enteredAmount: { currency: "BDT", amount: 8000 },
          matchStatus: "UNMATCHED",
          notes: "ডকুমেন্ট আংশিক এবং টাকার পরিমাণে অসামঞ্জস্য পাওয়া গেছে।",
          invoice: {
            id: "INV-2",
            name: "Invoice_Toner.pdf",
            sizeText: "1.8 MB",
            uploadedOn: "20 May",
          },
          status: "PENDING",
          totalAmount: { currency: "BDT", amount: 12000 },
          pendingAmount: { currency: "BDT", amount: 4000 },
          transactions: [
            {
              id: "TX-3",
              date: "৩ মে ২০২৪",
              refNo: "REF-998211",
              amount: { currency: "BDT", amount: 8000 },
              status: "REJECTED",
            },
          ],
        },
        vendor: {
          status: "LOCKED",
          invoiceTotal: { currency: "BDT", amount: 100000 },
          officeAdvancePercent: 80,
          officeAdvanceAmount: { currency: "BDT", amount: 80000 },
          vendorDuePercent: 80,
          vendorDueAmount: { currency: "BDT", amount: 80000 },
          pendingAmount: { currency: "BDT", amount: 0 },
          bank: {
            bankName: "সোনালী ব্যাংক পিএলসি",
            accountName: "মেসার্স রবিন এন্টারপ্রাইজ",
            accountNo: "১২৩৪৫৬৭৮৯০",
            routingNo: "০৩০২৬১...",
            branchName: "মটিহিল কর্পোরেট শাখা",
          },
        },
      },
      shipment: {
        status: "AGENT_ASSIGNED",
        agent: {
          id: "AG-1",
          name: "মোঃ আব্দুল করিম",
          phone: "০১৭০০-১১১২৩৩",
          deliveriesCount: 142,
          status: "ACTIVE",
        },
        courierName: "সুন্দরবন কুরিয়ার সার্ভিস",
        trackingId: "TRK-9921-22-SA",
        estDelivery: "২৭ অক্টোবর ২০২৪",
        notes: "পণ্যগুলো সুরক্ষিতভাবে প্যাকেজিং করা হয়েছে।",
        evidence: {
          id: "EV-1",
          name: "Mushak-6.3.pdf",
          sizeText: "1.2 MB",
          uploadedOn: "24 Oct, 2024",
        },
      },
      settlement: {
        status: "READY",
        total: { currency: "BDT", amount: 8000 },
        cleared: { currency: "BDT", amount: 8000 },
        pending: { currency: "BDT", amount: 0 },
        deductions: [],
        ledgerRows: [],
      },
    },
  ],
};
