import { BudgetReportRow, BudgetStatCard, BudgetFiltersState } from "../_types/budget-report.types";

export const demoBudgetStats: BudgetStatCard[] = [
  {
    id: "total",
    labelBn: "মোট টিআপিপত্র",
    value: 854,
    chipText: "+12.5%",
    iconType: "doc",
    accent: "primary",
  },
  {
    id: "remaining",
    labelBn: "যাচাইকরণ বাকি",
    value: 22,
    chipText: "আবশ্যক প্রক্রিয়ায়",
    iconType: "cal",
    accent: "orange",
  },
  {
    id: "submitted",
    labelBn: "অনুমোদিত",
    value: 712,
    suffixBn: "এই মাসে",
    iconType: "check",
    accent: "green",
  },
  {
    id: "rejected",
    labelBn: "প্রত্যাখ্যাত",
    value: 120,
    suffixBn: "মোট টাকা",
    iconType: "x",
    accent: "red",
  },
];

export const demoInitialFilters: BudgetFiltersState = {
  officeCode: "all",
  hierarchy: "all",
  dateFrom: "2024-07-01",
  dateTo: "2024-07-31",
};

export const demoBudgetRows: BudgetReportRow[] = [
  {
    id: "1",
    ministryBn: "প্রাথমিক ও গণশিক্ষা মন্ত্রণালয়",
    date: "12 Oct 2023",
    officeNameBn: "উপজেলা শিক্ষা অফিস",
    officeSubBn: "অফিস কোড: ০০১-০২",
    orgCode: "1250101",
    itemCount: 12,
    amount: 45000,
    status: "Pending",
    actionLabelBn: "যাচাই করুন",
  },
  {
    id: "2",
    ministryBn: "স্বাস্থ্য ও পরিবার কল্যাণ মন্ত্রণালয়",
    date: "11 Oct 2023",
    officeNameBn: "স্বাস্থ্য অধিদপ্তর",
    officeSubBn: "অফিস কোড: ০০১-০১",
    orgCode: "1270201",
    itemCount: 5,
    amount: 120000,
    status: "In Review",
    actionLabelBn: "যাচাই করুন",
  },
  {
    id: "3",
    ministryBn: "কৃষি মন্ত্রণালয়",
    date: "10 Oct 2023",
    officeNameBn: "কৃষি সম্প্রসারণ অধিদপ্তর",
    officeSubBn: "অফিস কোড: ০০৩-০১",
    orgCode: "1310301",
    itemCount: 45,
    amount: 850000,
    status: "Approved",
    actionLabelBn: "রিভিউ দেখুন",
  },
  {
    id: "4",
    ministryBn: "ডাক, টেলিযোগাযোগ ও তথ্যপ্রযুক্তি মন্ত্রণালয়",
    date: "09 Oct 2023",
    officeNameBn: "বিটিআরসি",
    officeSubBn: "অফিস কোড: ০০৫-০০",
    orgCode: "1420101",
    itemCount: 8,
    amount: 15000,
    status: "Pending",
    actionLabelBn: "যাচাই করুন",
  },
  {
    id: "5",
    ministryBn: "ভূমি মন্ত্রণালয়",
    date: "08 Oct 2023",
    officeNameBn: "ভূমি রেকর্ড ও জরিপ অধিদপ্তর",
    officeSubBn: "অফিস কোড: ০০২-০২",
    orgCode: "1450201",
    itemCount: 20,
    amount: 230000,
    status: "In Review",
    actionLabelBn: "যাচাই করুন",
  },
];
