import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata: Metadata = {
  title: "Government_procurement",
  description: "Generated by create next app",
};

const publicSans = Public_Sans({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={publicSans.className}>
      <body>
        {children}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}