import type { RefundRequestQueueItem } from "../_types/refund-request-queue.type";

export const REFUND_REQUEST_QUEUE_DATA: RefundRequestQueueItem[] = [
  {
    id: "r1",
    orderId: "#REF-8892",
    dateBn: "২৪ অক্টোবর ২০২৪",
    officeNameBn: "নোয়াখালী সদর উপজেলা",
    officeCodeBn: "কোড: ৩৫৫৫",
    vendorNameBn: "এম.কে এন্টারপ্রাইজ",
    productSummaryBn: "৪৫ পেপার (৫০ রিম)",
    refundType: "full",
    amount: 6000,
    status: "pending",
  },
  {
    id: "r2",
    orderId: "#REF-8901",
    dateBn: "২৩ অক্টোবর ২০২৪",
    officeNameBn: "কৃষি সম্প্রসারণ অধিদপ্তর",
    officeCodeBn: "কোড: ৮১১২",
    vendorNameBn: "টেকনো ওয়ার্ল্ড",
    productSummaryBn: "ল্যাপটপ (১ টি)",
    refundType: "partial",
    amount: 120000,
    status: "in_review",
  },
  {
    id: "r3",
    orderId: "#REF-8742",
    dateBn: "২১ অক্টোবর ২০২৪",
    officeNameBn: "সড়ক ও জনপথ বিভাগ",
    officeCodeBn: "কোড: ২৯৬১",
    vendorNameBn: "স্মার্ট কার্নিশার",
    productSummaryBn: "অফিস চেয়ার (১০ টি)",
    refundType: "full",
    amount: 84000,
    status: "approved",
  },
  {
    id: "r4",
    orderId: "#REF-8661",
    dateBn: "১৯ অক্টোবর ২০২৪",
    officeNameBn: "স্বাস্থ্য অধিদপ্তর",
    officeCodeBn: "কোড: ১২৮৮",
    vendorNameBn: "মেট্রো সাপ্লাই",
    productSummaryBn: "সার্জিক্যাল মাস্ক (১০০০)",
    refundType: "full",
    amount: 8000,
    status: "approved",
  },
];