import { Orders } from "@/app/(office)/office/types/order-list-type";

export const orders: Orders[] = [
  {
    id: "1",
    ref: "#ORD-4921",
    title: "Office Laptops (Dell Latitude 5000)",
    status: "active",
    badgeLabel: "Active",
    meta1: "Vendor: TechSolutions Ltd.",
    meta2: "Date: Oct 24, 2023",
    stepCurrent: "processing",
    totalAmountText: "৳ ৫৬,০০০",
    dueAmountText: "৳ ৫৬,০০০",
  },
  {
    id: "2",
    ref: "#ORD-4918",
    title: "Stationery Supplies Batch A",
    status: "shipped",
    badgeLabel: "Shipped",
    meta1: "Courier: Sundarban Courier",
    meta2: "Tracking:",
    stepCurrent: "in_transit",
    trackingCode: "SD-882190",
    totalAmountText: "৳ ৫৬,০০০",
    dueAmountText: "৳ ২০,০০০",
  },
  {
    id: "3",
    ref: "#REQ-1102",
    title: "Office Chairs (Ergonomic Mesh) - 50 Units",
    status: "pending_quote",
    badgeLabel: "Waiting for Quotes",
    meta1: "Requested by: Admin Dept.",
    meta2: "Due: Oct 30, 2023",
    quotesReceivedCount: 0,
  },
  {
    id: "4",
    ref: "#REQ-1102",
    title: "Office Chairs (Ergonomic Mesh) - 50 Units",
    status: "pending_quote",
    badgeLabel: "Waiting for Quotes",
    meta1: "Requested by: Admin Dept.",
    meta2: "Due: Oct 30, 2023",
    quotesReceivedCount: 3,
    peopleCount: 4,
  },
  {
    id: "5",
    ref: "#DRF-1102",
    title: "Office Chairs (Ergonomic Mesh) - 50 Units",
    status: "draft",
    badgeLabel: "খসড়া হিসাবে সংরক্ষিত",
    dueDateText: "Due: Oct 30, 2023",
    itemsAddedText: "২ টি আইটেম যোগ করা হয়েছে",
  },
];
