import { ProcurementCategory } from "@/app/(office)/office/types/procurement-product-type";

export const ProcurementCategories: ProcurementCategory[] = [
  {
    id: "1",
    code: "০২৫০৫০৫",
    titleBn: "অন্যান্য মনিহার",
    titleEn: "Other Stationery",
    balance: 5000,
    isAvailable: true,
    iconKey: "stationery",
  },
  {
    id: "2",
    code: "০২৫০৫০১",
    titleBn: "কম্পিউটার সামগ্রী",
    titleEn: "Computer Consumables",
    balance: 12600,
    isAvailable: true,
    iconKey: "computer",
    products: [
      {
        id: "p1",
        code: "০২৫০৫০১",
        name: "HP 85A Laserjet Toner",
        description: "Original Black, 1600 pages yield, Compatible with...",
        unit: "Piece",
        unitPriceMin: 3000,
        unitPriceMax: 3500,
        quantity: 0,
      },
      {
        id: "p2",
        code: "০২৫০৫০২",
        name: "Dell Wired Optical Mouse",
        description: "USB Interface, Black, 1000 DPI, Plug & Play",
        unit: "Piece",
        unitPriceMin: 450,
        unitPriceMax: 600,
        quantity: 5,
      },
      {
        id: "p3",
        code: "০২৫০৫০৩",
        name: "Logitech K120 Keyboard",
        description: "Standard USB, Spill-resistant, Bangla Layout printed",
        unit: "Piece",
        unitPriceMin: 800,
        unitPriceMax: 950,
        quantity: 0,
      },
      {
        id: "p4",
        code: "০২৫০৫০৪",
        name: "A4 Paper (Double A)",
        description: "80 GSM, 500 Sheets per ream, High quality white",
        unit: "Piece",
        unitPriceMin: 450,
        unitPriceMax: 550,
        quantity: 2,
      },
      {
        id: "p5",
        code: "০২৫০৫০৫",
        name: "Transcend Pen Drive 64GB",
        description: "USB 3.1, JetFlash 790K, Black, Capless",
        unit: "Piece",
        unitPriceMin: 700,
        unitPriceMax: 850,
        quantity: 0,
      },
    ],
  },
  {
    id: "3",
    code: "০৪১০১০৮",
    titleBn: "আসবাবপত্র",
    titleEn: "Furniture",
    balance: 0,
    isAvailable: false,
    iconKey: "furniture",
  },
  {
    id: "4",
    code: "০২৫০৫০২",
    titleBn: "বিশেষ বরাদ্দ",
    titleEn: "Special Budget",
    balance: 8750,
    isAvailable: true,
    iconKey: "printing",
  },
  {
    id: "5",
    code: "০২৫০৫০৩",
    titleBn: "পরিষ্কার পরিচ্ছন্নতা সামগ্রী",
    titleEn: "Cleaning Supplies",
    balance: 3200,
    isAvailable: true,
    iconKey: "cleaning",
  },
  {
    id: "6",
    code: "০৪১০১০৬",
    titleBn: "মোটরযান খুচরা যন্ত্রাংশ",
    titleEn: "Motor Vehicle Spares",
    balance: 0,
    isAvailable: false,
    iconKey: "vehicle",
  },
  {
    id: "7",
    code: "০২৫০৫০৪",
    titleBn: "বৈদ্যুতিক সরঞ্জাম",
    titleEn: "Electrical Goods",
    balance: 21800,
    isAvailable: true,
    iconKey: "electrical",
  },
  {
    id: "8",
    code: "০২৫০৫০৮",
    titleBn: "ঔষধ ও শল্য চিকিৎসা",
    titleEn: "Medical Supplies",
    balance: 50000,
    isAvailable: true,
    iconKey: "medical",
  },
];
